algoritmo "MostrarNome"

var
// texto - caractere - string
// verdadeiro/falso - logico - boolean
// numero inteiro - inteiro - int
// numero decimal - real - float
nomeUsuario : caractere

inicio
// output - saída - telas, leds , resposta por voz , som
// input - entrada - teclado , mouse , microfone
// l - line break - quebra de linha

// nomeUsuario <- "Filipe"
escreval("Digite seu nome: ")
leia(nomeUsuario)
escreva("Oi, ")
escreval("Bom dia "+nomeUsuario)

fimalgoritmo